# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lSUcMl3DLmN4ByQQyRNUTi1g+Ryc4+uB64qsKWv7KPozhZdt2d/WykivpHOgXPW4dLtUGqY3J+qGa169kinlWGM9F5YPg/8jSEiZjhSXd4Q54hK7LgBB1QIa1tspEGlNFADPL/Ex0X9fPXADC0yVk+/7ZhU097dtZMdBp68LGLtZVMT0hL5n+YhLU8RPFaccACLwjgYnXNl0jnnKDTFAzm+a6YtI4JIDWOVSMa/bLUsPhxB3du+nbASYDkyx1xhIJsryoA6/NSMuwxqoNb1hVpDWxZHlEMvo2DFp0SOthh/aeMRMI7UudI74pAkLcgy3nBLh6UHq+xqJEiylSo7MMAqgIpoVPiCEs6cGFbvCxpHV8gkuEKOm2uQNkFnLAKwAKKdsAs+/CteR+8DX04WK0dhrd1o+a7z1H/7C6/eATIL6duULIJkStk5BpTnfrDH38efHodxCg3s7TyRpBOH6bRVRdri+z3Dpf3OJx8ltDJljv7lTEF+jG9+11tH1qmfctvgjqlEpqIu8NxqVhsfdOT9VixP5lV/ty57e/MetmzPVNsADcE8y37NrgOcs3pNHZalKJ0Ox/GQVY0nsyxUILO3cBgHoCk7MwhBj1NxLBDeH8K4zY41DyYeteD0KtgnWh/hrE+f3iQNXnj99rf+CRtZmfRlsTa//NGy17kSR9hA="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
