travis:
  secure:
    BINSTAR_TOKEN: lSUcMl3DLmN4ByQQyRNUTi1g+Ryc4+uB64qsKWv7KPozhZdt2d/WykivpHOgXPW4dLtUGqY3J+qGa169kinlWGM9F5YPg/8jSEiZjhSXd4Q54hK7LgBB1QIa1tspEGlNFADPL/Ex0X9fPXADC0yVk+/7ZhU097dtZMdBp68LGLtZVMT0hL5n+YhLU8RPFaccACLwjgYnXNl0jnnKDTFAzm+a6YtI4JIDWOVSMa/bLUsPhxB3du+nbASYDkyx1xhIJsryoA6/NSMuwxqoNb1hVpDWxZHlEMvo2DFp0SOthh/aeMRMI7UudI74pAkLcgy3nBLh6UHq+xqJEiylSo7MMAqgIpoVPiCEs6cGFbvCxpHV8gkuEKOm2uQNkFnLAKwAKKdsAs+/CteR+8DX04WK0dhrd1o+a7z1H/7C6/eATIL6duULIJkStk5BpTnfrDH38efHodxCg3s7TyRpBOH6bRVRdri+z3Dpf3OJx8ltDJljv7lTEF+jG9+11tH1qmfctvgjqlEpqIu8NxqVhsfdOT9VixP5lV/ty57e/MetmzPVNsADcE8y37NrgOcs3pNHZalKJ0Ox/GQVY0nsyxUILO3cBgHoCk7MwhBj1NxLBDeH8K4zY41DyYeteD0KtgnWh/hrE+f3iQNXnj99rf+CRtZmfRlsTa//NGy17kSR9hA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
